version : 2 

models:
  - name: stg_customers
    description: "Customer Information"
    columns:
      - name: id
        description: "Event id"
        tests:
          - unique
          - not_null
          - is_integer

      - name: Kdnr
        description: "Customer number"
        tests: 
          - not_null
          - is_integer
          - accepted_values:
              values: ['>= 10000', '<= 99999']
              config:
                severity: warn

      - name: Verlagsname
        description: "Published name"
        tests:
          - not_null:
              config:
                severity: warn

      - name: Region
        description: "Region"




  - name: stg_invoices
    description: "Invoice Information"
    columns:
      - name: ReNummer
        description: "Invoice number"
        tests: 
          - unique
          - not_null 
          - is_integer
      
      - name: SummeNetto
        description: "Net Total"
    
      - name: MwStSatz
        description: "VAT rate"
        tests:
          - not_null
          - is_integer
      
      - name: ZahlungsbetragBrutto
        description: "Gross payment amount"
        tests: 
          - not_null
          - is_float:
              config:
                severity: warn
      
      - name: Kdnr
        description: "Customer number"
        tests: 
          - not_null:
            config:
                severity: warn
          - is_integer
          - accepted_values:
              values: ['>= 10000', '<= 99999']
      
      - name: Summenebenkosten
        description: "Total additional costs"
        tests: 
          - is_float
      
      - name: ReDatum
        description: "Invoice date"
        tests: 
          - not_null:
              config:
                severity: warn
          - is_date
      
      - name: Zahlungsdatum
        description: "Payment date"
        tests: 
          - is_date:
              config:
                severity: warn
          - dbt_utils.expression_is_true:
              expression: "Zahlungsdatum >= ReDatum OR Zahlungsdatum IS NULL"
              config:
                severity: warn

  

  
  - name: stg_positions
    description: "Customer positions"
    columns:
      - name: id
        description: "Position id"
        tests: 
          - unique
          - not_null
          - is_integer
      
      - name: ReId
        description: "Invoice id"
        tests: 
          - not_null:
              config:
                severity: warn
          - is_integer
      
      - name: KdNr
        description: "Customer number"
        tests: 
          - not_null:
              config:
                severity: warn
      
      - name: Nettobetrag
        description: "Net amount"
      
      - name: Bildnummer
        description: "Image number"
        tests: 
          - is_integer

      - name: VerDatum
        description: "Image date"
        tests: 
          - is_date:
              config:
                severity: warn