version: 2

models:
  - name: stg_customers
    description: "Customer Information"
    columns:
      - name: id
        description: "Event id"
        tests:
          - unique
          - not_null

      - name: Kdnr
        description: "Customer number"
        tests: 
          - not_null:
              config:
                severity: warn

      - name: Verlagsname
        description: "Published name"
        tests:
          - not_null:
              config:
                severity: warn

      - name: Region
        description: "Region"

  - name: stg_invoices
    description: "Invoice Information"
    columns:
      - name: ReNummer
        description: "Invoice number"
        tests: 
          - unique
          - not_null 
      
      - name: SummeNetto
        description: "Net Total"
      
      - name: MwStSatz
        description: "VAT rate"
        tests:
          - not_null:
              config:
                severity: warn
      
      - name: ZahlungsbetragBrutto
        description: "Gross payment amount"
        tests: 
          - not_null:
              config:
                severity: warn
      
      - name: Kdnr
        description: "Customer number"
        tests: 
          - not_null:
              config:
                severity: warn
      
      - name: Summenebenkosten
        description: "Total additional costs"
       
      - name: ReDatum
        description: "Invoice date"
        tests: 
          - not_null:
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
              config:
                  severity: warn
      
      - name: Zahlungsdatum
        description: "Payment date"
        tests:
          - not_null:
              config:
                severity: warn 
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
              config:
                  severity: warn

  - name: stg_positions
    description: "Customer positions"
    columns:
      - name: id
        description: "Position id"
        tests: 
          - unique
          - not_null
      
      - name: ReId
        description: "Invoice id"
        tests: 
          - not_null:
              config:
                severity: warn
      
      - name: KdNr
        description: "Customer number"
        tests: 
          - not_null:
              config:
                severity: warn
      
      - name: Nettobetrag
        description: "Net amount"
      
      - name: Bildnummer
        description: "Image number"

      - name: VerDatum
        description: "Image date"
        tests:
          - not_null:
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date
              config:
                  severity: warn